- app/src/main/java/com/milkyway/milkyway/ui/home/HomeBottomSheetViewModel.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/bindingAdapter.kt
- app/src/main/res/drawable-v24/selector_home_bottomsheet_text_color.xml
- app/src/main/res/drawable/border_gray_line_circle.xml
- app/src/main/res/drawable/border_navy_fill_circle.xml
- app/src/main/res/drawable/border_white_fill_round.xml
- app/src/main/res/drawable/selector_home_bottomsheet_location.xml
- app/src/main/res/layout/bottom_sheet_home.xml
- app/src/main/res/layout/fragment_home.xml
- 바텀 시트 그리기
- 데이터 바인딩
- 뷰모델 적용
- 클릭이벤트
> [feature] #9 Home Bottom Sheet - click event & viewModel

- app/src/main/res/layout/activity_nickname.xml
- set Color NicknameActivity
- set Font NicknameActivity
> [layout] #23 Setting Color & Font in NicknameActivity

- app/src/main/res/color/selector_home_chip_color.xml
- app/src/main/res/color/selector_home_chip_text_color.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- ChipGroup
- ChipColor
- ChipTextColor
> [layout] #10 ChipGroup in HomeFragment

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/res/layout/fragment_universe.xml
- NaverMap in UniverseFragment
- Setting Lightness(-0.7f)
> [layout] #27 Setting NaverMap in UniverseFragment

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/data/remote/RetrofitBuilder.kt
> [network] #31 Network Initial Setting

- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameViewModel.kt
- app/src/main/res/layout/activity_nickname.xml
> [network] #34 SignUp

- app/src/main/java/com/milkyway/milkyway/data/model/ReponseToken.kt
- app/src/main/java/com/milkyway/milkyway/data/model/RequestSign.kt
- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashViewModel.kt
- app/src/main/java/com/milkyway/milkyway/util/UUID.kt
- app/src/main/res/layout/activity_splash.xml
> [network] #35 SignIn

- app/build.gradle
- app/src/main/java/com/milkyway/milkyway/util/DataStore.kt
> [feature] #39 DataStore

- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameActivity.kt
- Datastore.setNickname in NicknameActivity
> [feature] #42 Save Nickname in NicknameActivity

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/res/values/strings.xml
> [feature] #45 setting nickname in HomeFragment

- app/src/main/java/com/milkyway/milkyway/util/DataStore.kt
> [feature] #52 Feat Save Token in DataStore

- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameViewModel.kt
- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashViewModel.kt
- SplashActivity
- NicknameActivity
> [feature] #53 Save Token After SignIn

- app/src/main/res/layout/fragment_home.xml
> [layout] #56 Home Card Layout

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- setOnMapClickListener
- setMapClick() in HomeViewModel
> [feature] #58 Card Layout Visibility

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
- Delete setVisibility
- Setting android:visibility
> [refactor] #65 Card Layout Visibility

- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameActivity.kt
> [feature] #60 statusBar Color in NicknameActivity

- app/src/main/res/layout/activity_nickname.xml
> [layout] #68 Delete Shadow in NicknameActivity

- app/src/main/java/com/milkyway/milkyway/data/model/ResponseHome.kt
- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
> [network] #71 Network in HomeFragment

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- Setting List Marker
- MarkerDrawer
> [feature] #73 Draw Marker List

- app/src/main/res/layout/fragment_home.xml
- Refactoring layout fragment_home
> [refactor] #84 layout Refactoring fragment_home

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- setMarkerClick in HomeViewModel
- setClickListener(onClick : () -> Unit)
> [feature] #86 card visibility switch

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/res/values/strings.xml
- init in MarkerDrawer
- cardData in MarkerDrawer
> [feature] #83 Card Data Setting

- app/src/main/java/com/milkyway/milkyway/data/model/ResponseHome.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
> [refactor] #98 data class responseHomeData

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeBinding.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- app/src/main/java/com/milkyway/milkyway/ui/report/myreport/CancelAdapter.kt
- app/src/main/res/layout/fragment_home.xml
#101 current location bottom margin using BindingAdapter
> [layout] #101 current location bottom margin using BindingAdapter

- app/src/main/java/com/milkyway/milkyway/data/model/ResponseUniverse.kt
- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseViewModel.kt
- app/src/main/res/layout/fragment_universe.xml
> [network] #107 UniverseFragment

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- app/src/main/res/layout/fragment_universe.xml
- app/src/main/res/values/strings.xml
- Layout card in UniverseFragment
- setMapClickListener in UniverseFragment
> [layout] #113 Universe Card Layout

- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- Clear in MarkerDrawer
- Clear in UniverseMarkerDrawer
> [feature] #115 Clear Marker List

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- MarkerDrawer.setIcon() in setMapClickListener
- UniverseMarkerDrawer.setIcon() in setMapClickListener
> [fix] #117 Setting Marker Size After Map Click

- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
> [feature] #119 Universe Card Data

- app/src/main/res/drawable/border_white_fill_top_round_8.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_universe.xml
> [layout] #121 Card Layout Drawable Modify

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
> [feature] #123 Visibility Setting In onResume()

- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
> [feature] #128 isHideCollidedMarkers

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
- chip.setOnCheckedChangeListener
> [feature] #90 Home Category Select Listener

- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- app/src/main/res/layout/fragment_home.xml
- network Category in HomeFragment
> [network] #131 Category Select Network in HomeFragment

- app/src/main/java/com/milkyway/milkyway/ui/nickname/NicknameActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashActivity.kt
- app/src/main/java/com/milkyway/milkyway/util/startActivity.kt
- startActivity
- finish() in NicknameActivitiy
- finish() in SplashActivity
> [fix] #140 BackStack

- app/src/main/java/com/milkyway/milkyway/data/model/RequestCafeId.kt
- app/src/main/java/com/milkyway/milkyway/data/model/ResponseAddUniverse.kt
- app/src/main/java/com/milkyway/milkyway/data/model/ResponseHome.kt
- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- add My Universe in HomeFragment
- add addMyUniverseHome in MilkyWayService
- add data class
> [feature] #144 Add My Universe in HomeFragment

- app/src/main/java/com/milkyway/milkyway/data/remote/MilkyWayService.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- delete universe in HomeFragment
> [feature] #154 Delete My Universe in HomeFragment

- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- Setting Icon Add Universe
- Setting Icon Delete Universe
> [feature] #158 Setting Icon after Add and Delete Universe

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- click Listener Reset after Add Universe
- click Listener Reset after delete Universe
> [feature] #160 Click Listener Reset

- app/src/main/java/com/milkyway/milkyway/ui/splash/SplashActivity.kt
> [fix] #162 add whenResumed in lifecycleScope

- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- delete isHideCollidedMarkers
> [refactor] #164 Delete isHideCollidedMarkers

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
> [feature] #167 addOnCameraChangeListener in UniverseFragment

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/res/values/strings.xml
> [refactor] #170 AndroidManifest

- app/src/main/java/com/milkyway/milkyway/ui/universe/MyUniverseListAdapter.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- RecyclerView Setting Data
- Adapter data class Modify
> [feature] #172 Bottom Sheet RecyclerView Set Data

- app/src/main/java/com/milkyway/milkyway/data/model/ResponseHome.kt
- app/src/main/java/com/milkyway/milkyway/data/model/ResponseUniverse.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- MarkerDrawer
- viewLifecycleOwner
> [refactor] #177 HomeFragment

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- HomeFragment to CafeDetail Activity
- UniverseFragment to CafeDetail Activity
> [feature] #176 Start CafeDetail Activity

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- app/src/main/java/com/milkyway/milkyway/util/Toast.kt
- app/src/main/res/drawable/border_black_fill_round_4.xml
- app/src/main/res/layout/item_custom_toast.xml
- app/src/main/res/values/colors.xml
- toast after add universe
- toast after delete universe
> [feature] #180 customToast

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseAdapter.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseBinding.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/res/layout/bottom_sheet_universe.xml
- app/src/main/res/layout/item_myuniverse_bottomsheet.xml
> [feature] #183 UniverseBinding

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseAdapter.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- From UniverseBottomSheet to CafeDetailActivity
> [feature] #188 From UniverseBottomSheet to CafeDetailActivity

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- UniverseMarkerDrawer
- UniverseFragment
> [refactor] #190 UniverseFragment

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeResultActivity.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/HomeViewModel.kt
- app/src/main/java/com/milkyway/milkyway/ui/home/homesearch/CafeSearchActivity.kt
- app/src/main/res/layout/activity_home_result.xml
> [feature] #146 Move After Search

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeResultActivity.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- Find Cafe Data in MarkerDrawer
- Setting Card Data in HomeResultActivity
> [feature] #201 Find Cafe Data

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeResultActivity.kt
- add universe
- delete universe
> [network] #203 HomeResultActivity Add/Delete Universe

- app/src/main/java/com/milkyway/milkyway/ui/home/HomeResultActivity.kt
- app/src/main/java/com/milkyway/milkyway/util/MarkerDrawer.kt
- return Index in MarkerDrawer
- UpdateData in MarkerDrawer
> [fix] #211 Update Cafe Data

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseAdapter.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseBinding.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseViewModel.kt
- BottomSheet Delete Universe in UniverseFragment
> [feature] #185 BottomSheet Delete Universe in UniverseFragment

- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseAdapter.kt
- app/src/main/java/com/milkyway/milkyway/ui/universe/UniverseFragment.kt
- app/src/main/java/com/milkyway/milkyway/util/UniverseMarkerDrawer.kt
- Card Layout Delete Universe in UniverseFragment
> [feature] #217 Card Layout Delete Universe in UniverseFragment
